<?php
$tarot_links = array(
    1 => "https://www.gnosisinternacional.com/tarot-carta-1/",
    2 => "https://www.gnosisinternacional.com/tarot-carta-2/",
    3 => "https://www.gnosisinternacional.com/tarot-carta-3/",
    4 => "https://www.gnosisinternacional.com/tarot-carta-4/",
    5 => "https://www.gnosisinternacional.com/tarot-carta-5/",
    6 => "https://www.gnosisinternacional.com/tarot-carta-6/",
    7 => "https://www.gnosisinternacional.com/tarot-carta-7/",
    8 => "https://www.gnosisinternacional.com/tarot-carta-8/",
    9 => "https://www.gnosisinternacional.com/tarot-carta-9/"
);

$zodiac_links = array(
    "aries" => "https://www.gnosisinternacional.com/signo-de-aries/",
    "tauro" => "https://www.gnosisinternacional.com/signo-de-tauro/",
    "geminis" => "https://www.gnosisinternacional.com/signo-de-geminis/",
    "cancer" => "https://www.gnosisinternacional.com/signo-de-cancer/",
    "leo" => "https://www.gnosisinternacional.com/signo-de-leo/",
    "virgo" => "https://www.gnosisinternacional.com/signo-de-virgo/",
    "libra" => "https://www.gnosisinternacional.com/signo-de-libra/",
    "escorpio" => "https://www.gnosisinternacional.com/signo-de-escorpio/",
    "sagitario" => "https://www.gnosisinternacional.com/signo-de-sagitario/",
    "capricornio" => "https://www.gnosisinternacional.com/signo-de-capricornio/",
    "acuario" => "https://www.gnosisinternacional.com/signo-de-acuario/",
    "piscis" => "https://www.gnosisinternacional.com/signo-de-piscis/"
);

$tonic_results = array(
    1 => "Tienes capacidad para vencer obstáculos, iniciativas positivas, voluntad, virtud, perseverancia, triunfo ante lo adverso, ASPECTO NEGATIVO: Vanidad, Egoísmo.",
    2 => "Tienes Capacidad de observación. Ingenio para concertar negocios complicados, Manantial de vida, tu intuición no engaña, ASPECTO NEGATIVO: inconstancia, torpeza.",
    3 => "Producción material y espiritual, sabes formar ideas ASPECTO NEGATIVO: Ostentación y desenfreno",
    4 => "La Cruz de la Iniciación, Progreso, éxito, elevación espiritual ASPECTO NEGATIVO: obstinación y excentricidad",
    5 => "Hombre regenerándose o perdiéndose, Cooperación inesperada; ayuda de iguales o superiores, Mano amiga y pródiga ASPECTO NEGATIVO: entrometismo e inconstancia.",
    6 => "El enamorado, La victoria. Buena suerte. Envidias en acecho; trampas importunas; confianzas traicioneras, amigos engañosos, intrigantes. ASPECTO NEGATIVO: lascivia y contradicción ",
    7 => "Impulsos y deseos de superación, sus esfuerzos hallan recompensa, ASPECTO NEGATIVO: obsesión y ofuscación ",
    8 => "Pruebas y dolores, iniciación, La ley del equilibrio, Evolución e involución, atracción y rechazo. Hallazgo productivo ASPECTO NEGATIVO: falsía y desconfianza",
    9 => "Concreción, culminación y elevación de anhelos, Una palabra demás que lo desprestigia, ASPECTO NEGATIVO: agresividad y violencia"
);

$urgency_results = array(
    1 => "Trabajar con la mente, Sé en tus obras como eres en tus pensamientos, eliminar dudas y demoras",
    2 => 'El Espíritu y la materia viven en eterna lucha, Pedid y se os Dará, integración con la madre divina, Juego de Opuestos, El viento y las olas van siempre en favor de quien sabe navegar". prudencia en la generosidad indiscriminada. Trabajar con la Ira.',
    3 => "Encarnar el Verbo, la palabra, Tejiendo está tu telar, telas para tu uso y telas que no has de usar, matrimonio, aproveche las oportunidades, eliminar la duda",
    4 => "Al trabajo de tus manos, da bendición y en el del pensamiento, pon razón, Distanciamientos; frialdad afectiva; desconcierto",
    5 => "No juzgar para no ser juzgados, toma en sus manos las riendas de su propio destino y se convierte en ángel o demonio, De oídas te había oído; más ahora mis ojos te ven y mi corazón te siente.",
    6 => "Determinación de estado, Trabajos me das señor, más con ellos fortaleza, No se deje tentar; fije sus posiciones; guíese por lo espiritual, seguridad de sí mismo",
    7 => "Eliminación de dudas y errores, Cuando la ciencia entre a tu corazón y la sabiduría sea dulce a tu alma, pide y te será dado, lamentaciones inútiles",
    8 => "Se necesita una gran paciencia para no caer en el Abismo... ¡Somos probados muchas veces, paciencia de Job, Edifica un altar en tu corazón, mas no hagas de tu corazón un altar, no divague; recuerdos exhumados que atormentan, Ruptura; disensiones; altercados; separación.",
    9 => "Ausencia de equilibrio interior, Afirme su discreción, medite sobre la oportunidad de su anhelo, debe ser humilde para alcanzar la Sabiduría y después de lograrlo debe ser todavía más humilde que nadie, Sube al monte y contempla la tierra prometida; más no te digo que entrarás en ella."
);

$nature_results = array(
    1 => "Poder volitivo, Dominio de las fuerzas en movimiento, sanos ideales.",
    2 => "Pasión arrolladora, exaltación espiritual, riñas, ira, amarguras, disensiones",
    3 => "Expansión de ideas y deseos, atracción recíproca; besos castos.",
    4 => "Realización de cosas materiales. Contactos afectivos intensos control de lo material, erotismo",
    5 => 'el "Karma" del Iniciado, Dominio de las pasiones, Retracción; dilación; nostalgias persistentes, aislamiento.',
    6 => "El deseo, la mente, la mala voluntad, Lucha terrible entre el amor y el Deseo, Abstinencia y Gula, libertad y necesidad, deber y derecho, Cavilaciones constantes, callejón sin salida, abatimiento, desazones",
    7 => "dolor, amargura.",
    8 => "Modere sus ímpetus y deseos; no tome decisiones por hoy, relájese",
    9 => "ausencia de equilibrio interior, ser más discreto"
);

$physic_results = array(
    1 => "Llena tu cáliz (cerebro) con el vino sagrado de la luz -Rige la Cabeza",
    2 => "Intercambio, duplicidad. -Rige la Garganta y cuello",
    3 => "Trabajo con La energía sexual, -Rige la Nuca y los Brazos",
    4 => "Trabajar con los 4 elementos-Rige la Glandula Timo",
    5 => "El cuerpo como pentalfa-Rige el Corazon",
    6 => "El hombre entre el vicio y la Virtud-Rige Vientre e Intestinos",
    7 => "Trabajo en la alkimia para adquirir la espada-Rige los Riñones ",
    8 => "Gravitar en el corazon -Rige Organos Sexuales ",
    9 => "El sexo -Rige Arterias Femorales"
);

$talent_results = array(
    1 => "El verbo, la palabra, Mente superior, dignidad, iniciativa.",
    2 => "La ciencia oculta, Claridad conceptual, lucidez, criterio analítico",
    3 => "Conocimiento de lo oculto, ",
    4 => "Dominio de sí mismo, obediencia",
    5 => "Pentagrama esoterico, autoridad, Control de las fuerzas naturales, ",
    6 => "es la Suprema Afirmación del Cristo Interno y la Suprema Negación del Satán.",
    7 => "El espíritu gobierna la materia, Triunfo en lo que se propone, ",
    8 => "Muerte y resurreccion ",
    9 => "Intrepidez, hombre solitario, Amor divino, prudencia, Discreción, caridad y conocimiento"
);

$zodiac_results = array(
    "aries" => "Los nativos de Aries son de naturaleza guerrera, se encolerizan fuertemente y como quiera que poseen una gran energía marciana, se siente capaces de embarcarse en grandes empresas y de llevarlas a buen termino." . "Por lo común no son felices en el AMOR, pues la fácil irritabilidad que poseen los conduce a disgustos y separaciones conyugales. A los nativos de Aries les agrada mucho la vida independiente." . "El carácter de los Arianos prevalece el orgullo, la confianza en si mismos, la ambición y un valor verdaderamente loco. Les gusta ser independientes y la milicia aunque en esta no existe la Independencia.",
    "tauro" => "Los taurinos son mansos y trabajadores, pero cuando se enfurecen son terribles como el toro. Los TAURINOS pasan en su vida por GRANDES DECEPCIONES AMOROSAS, son reservados conservadores, siguen paso a paso, por el camino trazado. " . "Los TAURINOS son muy sensibles, la ira en los taurinos es de lento crecimiento y suelen estallar en fuertes estallidos volcánicos. " . "El tipo mediocre de taurus suele ser muy egoísta , glotón, pendenciero, pasional, iracundo, orgulloso." . "El tipo superior de taurus está lleno de AMOR, ama la música clásica, la sabiduría, trabaja con alegría por la humanidad, es muy inteligente, comprensivo, fiel, sincero en la amistad, buen padre, buen amigo, buen hermano, buen ciudadano, etc.",
    "geminis" => "Los nativos de Géminis son de recia voluntad; poseen gran valor, son versátiles y gustan de viajar. Sus vidas son una mezcla de éxitos y fracasos. A veces viven con comodidad y por tiempos tienen que soportar mucha miseria." . "Son muy inteligentes y se irritan fácilmente. El defecto de los nativos de Géminis es querer resolver todas las cosas con la cabeza. " . "Quieren siempre acallar la sabia voz del corazón y entonces se crean problemas y dificultades de toda índole. Los nativos de Géminis son problemáticos por su raro dualismo, por esa doble personalidad que los caracteriza. ". "En cualquier momento determinado el nativo de Géminis resulta un amigo muy sincero, capaz de sacrificar hasta su propia vida por la amistad, por la persona a la cual a ofrendado su cariño, pero en cualquier otro momento, es capaz de las peores infamias contra esa misma persona amada. ". "El defecto más grave de los nativos de Géminis es la tendencia a juzgar falsamente a todas las personas. ",
    "cancer" => "Tienen disposición para las artes manuales, son muy sensibles y su carácter cambia con las fases lunares.    Los cancerinos son pacíficos pero a veces demasiado coléricos. " . "Les va bien en viajes largos. Son románticos, amorosos y muy tenaces. " . "Los nativos de CÁNCER tienen viva imaginación, mas deben cuidarse de la fantasía. Los Cancerinos tienen naturaleza suave, retraída y encogida, virtudes caseras. " . "En CÁNCER encontramos a veces algunos individuos demasiado pasivos, flojos, perezosos.",
    "leo" => "Los nativos de Leo son enérgicos y bondadosos al mismo tiempo son magnánimos, místicos y autoritarios. Tienen tendencia a la ira, y deben luchar mucho para dominar ese defecto." . "Leo, siendo el trono del Sol, anuncia fortuna y posición elevada. El significado oculto de Leo es la Intuición. El metal de ese signo es el oro y la piedra el Diamante.". "Los nativos de Leo son autoritarios y solo quieren mandar." . "Leo trae algunos viajes. Moralmente sufren mucho los nativos de Leo. ". "Leo gobierna el corazón humano. El sol del organismo es el corazón; en el corazón las fuerzas de arriba se mezclan con las de abajo, para que las de abajo se liberen. El color de leo es el Dorado; En la práctica hemos podido verificar que los nativos de Leo son como el León, valientes, iracundos, nobles, dignos constantes. Empero gente hay mucha y es claro que entre los nativos de Leo también encontramos altaneros, orgullosos, infieles, tiranos, etc." . "Los nativos de Leo tienen aptitudes de organización, desarrollan el sentimiento y la bravura del León. Las personas desarrolladas de este signo, llegan a ser grandes paladines. " . "El tipo mediocre de Leo es muy sentimental e iracundo. El tipo mediocre de Leo sobreestima demasiado sus propias capacidades. En todo nativo de Leo existe siempre la mística ya elevada en estado incipiente; todo depende del tipo de persona. Los nativos de Leo están siempre predispuestos a sufrir accidentes de los brazos y de las manos.",
    "virgo" => "Virgo es el signo zodiacal de la virgen madre del mundo, es casa de mercurio, sus minerales son el jaspe y la esmeralda." . "En la vida practica hemos podido verificar que los nativos de virgo son desgraciadamente muy razonativos en exceso, más allá de lo normal y escépticos por naturaleza.". "Los nativos de virgo sirven para la ciencia, la psiquiatría, la medicina, el naturismo, el laboratorio, la pedagogía, etc., etc., etc. Los nativos de virgo no pueden entenderse con la gente de Piscis y por ello les aconsejamos evitar matrimonios con personas piscianas." . "Lo más lamentable de las gentes de virgo es esa inercia y escepticismo que les caracteriza. Sin embargo, resulta interesante saber que esa tensa inercia tiende a pasar de lo material a lo espiritual, hasta donde es accesible por medio de la experiencia." . "Por lo común abundan entre los mediocres de este signo, los materialistas ateos, enemigos de todo lo que huela a espiritualidad. El egoísmo de la gente mediocre de virgo, es algo demasiado grosero y asqueante, aun que también pueden ser geniales y altamente altruistas y profundamente desinteresados. " . "Los nativos de virgo sufren en el AMOR y pasan por grandes decepciones, debido a que Venus, el astro del AMOR, en virgo está en destierro.",
    "libra" => "En la práctica hemos podido verificar que los nativos de Libra suelen, en su mayoría, tener cierto desequilibrio en lo relacionado con vida conyugal, AMOR. Los nativos de Libra se crean muchos problemas por su manera de ser franca y justiciera." . "A los libranos bien aspectados, les gusta las cosas rectas y justas. La gente no entiende bien a los Libranos, éstos parecen a veces crueles y despiadados, no saben ni quieren saber de diplomacias, la hipocresía les fastidia, las dulces palabras de los perversos les enojan fácilmente en vez de suavizarles. " . "Los libranos tienen el defecto de no saber perdonar al prójimo, en todo quieren ver Ley y nada más que ley, olvidando muchas veces la misericordia. A los nativos de Libra les gusta muchísimo viajar y son fieles cumplidores de sus deberes. " . "Los nativos de Libra son lo que son y nada más que lo que son, francos y justicieros. Las gentes suelen enojarse con los nativos de Libra, se les interpreta erradamente por esa forma de ser y como es natural se habla mal de ellos y suelen llenarse de enemigos gratuitos. Al librano no se le puede venir con dobles juegos, eso no lo tolera el Librano y no lo perdona. Con los libranos se debe ser siempre amable y cariñoso o severo siempre, pero jamás con ese doble juego de dulzura y dureza, porque eso no lo tolera y no lo perdona jamás el librano." . "El tipo Superior de Libra confiere siempre castidad total. El tipo Inferior de Libra es muy fornicario y adúltero. El tipo superior de Libra tiene cierta espiritualidad que los espiritualistas no entienden y juzgan equivocadamente. El tipo inferior negativo de Libra, le agrada ponerse siempre en primera fila, llamar la atención de todo el mundo. El tipo superior de Libra quiere vivir siempre anónimo y desconocido, jamás siente atracción alguna por la fama, por los laureles, por el prestigio." . "El tipo medio de Libra suelen mezclarse muchas cualidades y defectos de los tipos superior e inferior de Libra. A los nativos de Libra les conviene matrimonio con piscianos. A los nativos de Libra les gusta hacer obras de caridad sin esperar recompensa ni alardear o publicar el servicio hecho. El tipo superior de Libra ama la música selecta, se recrea en ella y la goza en grado sumo. Los libranos sienten también atracción por el buen teatro, buena literatura, etc., etc., etc. ",
    "escorpio" => "En la práctica hemos podido verificar que los nativos de Escorpio sufren mucho en la primera mitad de la vida y hasta tienen un AMOR que les ocasiona grandes amarguras, pero en la segunda mitad de la vida todo cambia, la suerte le mejora notablemente. " . "Los nativos de Escorpio tienen cierta tendencia a la Ira y a la venganza, difícilmente perdonan a alguien. Las mujeres de Escorpio siempre están en el peligro de quedar viudas y pasar muchas necesidades económicas durante la primera parte de la vida, pero debido a la experiencia, mejoran en la segunda mitad de su existencia. " . "Los nativos de Escorpio son personas de energía, ambiciosos, reservados, francos, enérgicos. Los nativos de Escorpio, como amigos, son amigos de verdad, sinceros fieles, capaces de sacrificarse por la amistad, pero como enemigos, son muy temibles, vengativos, peligrosos.",
    "sagitario" => "En la práctica hemos podido verificar que los nativos de SAGITARIO son muy fornicarios y pasionales. Los nativos de SAGITARIO aman los viajes, las exploraciones, las aventuras, los deportes. Los nativos de SAGITARIO se enojan fácilmente y luego perdonan. " . "Los nativos de SAGITARIO son muy comprensivos, aman la bella música, poseen maravillosa inteligencia. Los sagitarianos son tenaces, cuando parece haber definitivamente fracasado, parecen resucitar de entre sus propias cenizas como el Ave Fénix de la mitología, dejando asombrados a todos sus amigos y enemigos. " . "Los nativos de SAGITARIO son capaces de embarcarse en grandes empresas, aun cuando se vean rodeados de inmensos peligros. " . "La vida económica de los Sagitarios a veces es muy buena, pero también pasan los sagitarianos por grandes amarguras y dificultades económicas. Lo que más perjudica a los sagitarianos es la lujuria.",
    "capricornio" => "Los nativos de Capricornio tienen disposición para la pedagogía, sufren mucho, tienen un gran sentido del deber, son prácticos por naturaleza y pasan en su vida siempre por un gran sufrimiento, alguien les traiciona. " . "Las mujeres de Capricornio son magníficas esposas, fieles hasta la muerte, hacendosas, trabajadoras, sufridas hasta lo indecible, pero a pesar de todas estas virtudes, el marido les traiciona, las abandona y muchas veces hasta contra su propia voluntad, es el karma de ellas desgraciadamente. " . "Algunas mujeres de Capricornio se meten con otros hombres, pero esto es solo estando ya abandonadas por el marido y después de haber sufrido espantosamente. " . "Los hombres y mujeres de Capricornio son bastante egoístas, aun cuando no todos; nos referimos al tipo inferior de Capricornio. Debido a esto, a ese egoísmo, contraen muchos compromisos y también se llenan de enemigos. " . "Los nativos de Capricornio se apegan muchísimo a las cosas, al dinero y algunos hasta se tornan muy avaros. Capricornio es un signo de tierra, fijo, estable. Sin embargo, los nativos de Capricornio realizan muchos viajes aun cuando sean cortos. " . "Los dolores morales de los capricornianos son terribles, sufren demasiado, afortunadamente su sentido practico de la vida los salva y bien pronto se sobreponen a las peores amarguras de la vida.",
    "acuario" => "Los nativos de Acuario tienen gran disposición para las ciencias naturales, medicina, química, botánica, astrología, biología, astronomía, etc., etc. Los nativos de Acuario son cada uno revolucionario a su modo, en su vida, en sus costumbres, en su casa, fuera de su casa, etc., etc., etc. Los nativos de acuario se destacan como paladines, algunos en grande, otros en pequeño, pero todos tienen una marcada tendencia a ser paladines." . "Los acuarianos de tipo superior son altruistas, filantrópicos, bondadosos, fieles en la amistad, sinceros, saben seleccionar sus amistades, por instinto; por intuición conocen a las personas y quieren siempre fraternidad, humanidad." . "El acuariano de tipo superior es preciso en sus cosas, concentrado, profundo, perseverante, maravilloso. Las mujeres de acuario son buenas esposas, buenas madres, pero les gusta estar fuera de casa y esto molesta mucho a los maridos, sobre todo si éstos son taurinos.",
    "piscis" => "Los nativos de Piscis por lo común tienen dos esposas, varios hijos. Son de naturaleza dual y tienen disposición para dos profesiones u oficios. Los nativos de Piscis son muy difíciles de comprender, viven como el pez, en todo, pero separados de todo por el líquido elemento. Se adaptan a todo, pero en el fondo desprecian todas las cosas del mundo. Son exquisitamente sensitivos, intuitivos, profundos y la gente no los puede comprender. " . "Los nativos de Piscis tienen gran disposición para el ocultismo, debido a que Piscis está gobernado por Neptuno, el planeta del esoterismo. Las mujeres de Piscis son muy nerviosas, sensitivas como una delicadísima flor; intuitivas, impresionables. Los piscianos tienen buenos sentimientos sociales, alegres, pacíficos, hospitalarios por naturaleza." . "El peligro de los piscianos es caer en la pereza, negligencia, pasividad e indiferencia por la vida. Los piscianos pueden llegar hasta a la falta de responsabilidad moral. La mente de los piscianos oscila entre comprensión rápida o fatal, pereza y desprecio por las cosas más necesarias para la vida. Son dos extremos y tan pronto caen en un extremo como en el otro. La voluntad de los piscianos a veces es fuerte, pero cambiante en otras ocasiones. " . "Cuando caen los piscianos en la indiferencia y pasividad extrema, se dejan llevar por la corriente del río de la vida, pero cuando ya ven la gravedad de su conducta, ponen en juego su voluntad de acero y entonces cambian radicalmente todo el curso de su existencia. " . "Los piscianos de tipo superior poseen una voluntad de acero inquebrantable y un elevadísimo sentido de responsabilidad moral. El tipo superior de Piscis da grandes iluminados, maestros, etc." . "El tipo inferior de Piscis tiene una marcada tendencia a la lujuria, alcoholismo, glotonería, pereza, orgullo. Los piscianos gustan de los viajes, mas no todos pueden viajar. Los piscianos tienen una gran imaginación y una tremenda sensibilidad. Resulta muy difícil comprender a los piscianos, sólo los piscianos pueden comprender a los piscianos." . "Todo lo que para la gente común y corriente tiene gran importancia, para los piscianos no vale nada, pero es diplomático, se adapta a las gentes, aparenta que está de acuerdo con ellas. Lo más grave para los nativos de Piscis, es tener que definirse en la cuestión conyugal, pues casi siempre dos Amores básico fundamentales, les meten en un callejón sin salida."
);

$fiftys = array(
    1 => "es bueno para iniciar todo lo que deseamos; un negocio, un viaje, matrimonio, en fin, todo lo que se deba comenzar",
    2 => "aun tu influencia te ayuda para iniciar positivamente todo lo que emprendas; misma vibracion pero menos que el primero, fechas especiales para resolver o iniciar todo lo que tenga relacion con papeleos.",
    3 => "en este periodo puede irte Regular, la vibracion se torna propicia para generar enredos.",
    4 => "este periodo es malo para papeleos, mantente alerta con tus finanzas",
    5 => "este periodo es bueno para emprender, amar, difundir, compartir, mantente alegre.",
    6 => "junto al primer 52 avo este es un periodo de exito, muy bueno para iniciar un negocio, un buen amor, compras acertadas, adelante en todo lo que emprendas.",
    7 => "muy malo para hacer cualquier negocio. Este ultimo 52 avo termina con tu cumpleaños, pero ten en cuenta que el dia de tu cumpleaños es especialmente peligroso, pues aun no haz nacido astrologicamente... cuidate bien ese dia hasta que llegue tu hora de nacimiento."
);
?>